import { Product, Vendor, Customer, InventoryItem } from './types';

export const sampleVendors: Omit<Vendor, 'id'>[] = [
    {
        name: 'Premium Supplies Co.',
        contactPerson: 'John Smith',
        phone: '555-0100',
        email: 'john@premiumsupplies.com',
        address: '123 Distribution Ave, Commerce City',
        taxId: 'TAX123456',
    },
    {
        name: 'Global Imports Ltd.',
        contactPerson: 'Maria Garcia',
        phone: '555-0101',
        email: 'maria@globalimports.com',
        address: '456 Trade Center, Import City',
        taxId: 'TAX789012',
    },
    {
        name: 'Local Producers Inc.',
        contactPerson: 'David Chen',
        phone: '555-0102',
        email: 'david@localproducers.com',
        address: '789 Manufacturing Way, Factory Town',
        taxId: 'TAX345678',
    },
];

export const sampleProducts: Omit<Product, 'id'>[] = [
    {
        name: 'Organic Milk 1L',
        sku: 'MLK001',
        barcode: '4006381333931',
        category: 'Dairy',
        description: 'Fresh organic milk, 1 liter',
        unit: 'pcs',
        costPrice: 1.50,
        retailPrice: 2.99,
        wholesalePrice: 2.50,
        minWholesaleQty: 10,
        stockLevel: 45,
        alertLevel: 10,
    },
    {
        name: 'Whole Wheat Bread',
        sku: 'BRD001',
        barcode: '5010029003346',
        category: 'Bakery',
        description: 'Fresh whole wheat bread loaf',
        unit: 'pcs',
        costPrice: 1.80,
        retailPrice: 3.49,
        wholesalePrice: 2.99,
        minWholesaleQty: 12,
        stockLevel: 32,
        alertLevel: 8,
    },
    {
        name: 'Free Range Eggs (12pc)',
        sku: 'EGG001',
        barcode: '4006381333922',
        category: 'Dairy',
        description: 'Free range chicken eggs, dozen',
        unit: 'box',
        costPrice: 2.50,
        retailPrice: 4.99,
        wholesalePrice: 4.20,
        minWholesaleQty: 8,
        stockLevel: 28,
        alertLevel: 6,
    },
    {
        name: 'Cheddar Cheese Block 500g',
        sku: 'CHE001',
        barcode: '3016200005641',
        category: 'Dairy',
        description: 'Aged cheddar cheese block',
        unit: 'pcs',
        costPrice: 4.00,
        retailPrice: 7.99,
        wholesalePrice: 6.50,
        minWholesaleQty: 6,
        stockLevel: 18,
        alertLevel: 5,
    },
    {
        name: 'Greek Yogurt 500g',
        sku: 'YOG001',
        barcode: '5410011814097',
        category: 'Dairy',
        description: 'Creamy Greek yogurt',
        unit: 'tub',
        costPrice: 1.25,
        retailPrice: 2.99,
        wholesalePrice: 2.40,
        minWholesaleQty: 12,
        stockLevel: 52,
        alertLevel: 12,
    },
    {
        name: 'Tomato Sauce 400ml',
        sku: 'SAU001',
        barcode: '8712566010235',
        category: 'Condiments',
        description: 'Sea sun tomato sauce',
        unit: 'can',
        costPrice: 0.80,
        retailPrice: 1.49,
        wholesalePrice: 1.20,
        minWholesaleQty: 20,
        stockLevel: 68,
        alertLevel: 15,
    },
    {
        name: 'Olive Oil 500ml',
        sku: 'OIL001',
        barcode: '8001471121205',
        category: 'Oils',
        description: 'Extra virgin olive oil',
        unit: 'bottle',
        costPrice: 3.50,
        retailPrice: 6.99,
        wholesalePrice: 5.99,
        minWholesaleQty: 6,
        stockLevel: 12,
        alertLevel: 4,
    },
    {
        name: 'Pasta 400g',
        sku: 'PAS001',
        barcode: '8001471050003',
        category: 'Dry Goods',
        description: 'Premium Italian pasta blend',
        unit: 'box',
        costPrice: 0.60,
        retailPrice: 1.29,
        wholesalePrice: 1.00,
        minWholesaleQty: 24,
        stockLevel: 95,
        alertLevel: 20,
    },
    {
        name: 'Orange Juice 1L',
        sku: 'JUI001',
        barcode: '5449000051159',
        category: 'Beverages',
        description: 'Fresh squeezed orange juice',
        unit: 'ltr',
        costPrice: 1.80,
        retailPrice: 3.49,
        wholesalePrice: 2.99,
        minWholesaleQty: 12,
        stockLevel: 38,
        alertLevel: 10,
    },
    {
        name: 'Coffee 250g',
        sku: 'COF001',
        barcode: '7622300040068',
        category: 'Beverages',
        description: 'Premium arabica coffee beans',
        unit: 'pack',
        costPrice: 4.50,
        retailPrice: 8.99,
        wholesalePrice: 7.50,
        minWholesaleQty: 8,
        stockLevel: 25,
        alertLevel: 6,
    },
];

export const sampleCustomers: Omit<Customer, 'id'>[] = [
    {
        name: 'ABC Supermarket',
        phone: '555-2001',
        email: 'orders@abcsuper.com',
        type: 'wholesale',
        totalSpent: 5240.50,
        creditLimit: 10000,
        outstandingBalance: 1200.00,
    },
    {
        name: 'Healthy Living Cafe',
        phone: '555-2002',
        email: 'manager@healthycafe.com',
        type: 'wholesale',
        totalSpent: 3890.75,
        creditLimit: 8000,
        outstandingBalance: 450.00,
    },
    {
        name: 'Downtown Restaurant',
        phone: '555-2003',
        email: 'chef@downtownrest.com',
        type: 'wholesale',
        totalSpent: 8750.25,
        creditLimit: 15000,
        outstandingBalance: 2100.00,
    },
    {
        name: 'Maria Rodriguez',
        phone: '555-2101',
        email: 'maria@email.com',
        type: 'retail',
        totalSpent: 245.80,
        outstandingBalance: 0,
    },
    {
        name: 'James Thompson',
        phone: '555-2102',
        email: null,
        type: 'retail',
        totalSpent: 128.50,
        outstandingBalance: 0,
    },
];

export const sampleInventoryItems: Omit<InventoryItem, 'id'>[] = [
    {
        productId: 1,
        vendorId: 1,
        quantity: 45,
        costPrice: 1.50,
        batchNumber: 'LOT2026001',
        expiryDate: new Date(2027, 8, 15),
        receivedDate: new Date(2026, 1, 15),
    },
    {
        productId: 2,
        vendorId: 2,
        quantity: 32,
        costPrice: 1.80,
        batchNumber: 'LOT2026002',
        expiryDate: new Date(2027, 10, 20),
        receivedDate: new Date(2026, 1, 18),
    },
    {
        productId: 3,
        vendorId: 1,
        quantity: 28,
        costPrice: 2.50,
        batchNumber: 'LOT2026003',
        expiryDate: new Date(2027, 4, 10),
        receivedDate: new Date(2026, 1, 19),
    },
    {
        productId: 5,
        vendorId: 3,
        quantity: 52,
        costPrice: 1.25,
        batchNumber: 'LOT2026004',
        expiryDate: new Date(2027, 1, 28),
        receivedDate: new Date(2026, 1, 20),
    },
    {
        productId: 6,
        vendorId: 2,
        quantity: 68,
        costPrice: 0.80,
        batchNumber: 'LOT2026005',
        expiryDate: new Date(2027, 5, 30),
        receivedDate: new Date(2026, 1, 21),
    },
];
